# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qol2CkE1VAuB_uDzDRZtH2jLL339y0GK
"""

!pip install streamlit

import streamlit as st
import pickle
import numpy as np

with open('/content/drive/MyDrive/model.pkl', 'rb') as f:
    model = pickle.load(f)

# Install Streamlit
!pip install streamlit

# Write your Streamlit app script
app_script = """
import streamlit as st
import pickle
import numpy as np


with open('your_model.pkl', 'rb') as f:
    model = pickle.load(f)


def predict(input_features):
    input_features = np.array(input_features)
    prediction = model.predict(input_features)
    return prediction


st.title('Your Model Predictor')


feature1 = st.slider('Feature 1', min_value=0.0, max_value=10.0, value=5.0)
feature2 = st.slider('Feature 2', min_value=0.0, max_value=10.0, value=5.0)


if st.button('Predict'):
    input_features = [[feature1, feature2]]
    prediction = predict(input_features)
    st.write('Prediction:', prediction)
"""

# Save the Streamlit app script to a file
with open('app.py', 'w') as f:
    f.write(app_script)

from google.colab import files
uploaded = files.upload()